version: "3.9"
services:
  web:
    build:
      context: .
    command: ["bundle", "exec", "rackup", "-p", "80", "-o", "0.0.0.0"]
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    depends_on:
      - chrome
  chrome:
    image: browserless/chrome
    ports:
      - "3333:3333"
    volumes:
      - .:/app:cached
    environment:
      PORT: 3333
      CONNECTION_TIMEOUT: 600000
